# Intered from https://english.stackexchange.com/questions/32447/is-there-an-extended-backus-naur-form-ebnf-that-covers-all-of-english

# Main sentence structures
SENTENCE  ::= STATEMENT | QUESTION | COMMAND

STATEMENT ::= ADJ+ ADVERB+ SUBJECT? ADJECTIVE+ VERB? " "

QUESTION  ::= ADJ+ ADVERB+ "DO " SUBJECT ADJECTIVE+ VERB? " "

COMMAND   ::= ADJ+ ADVERB+ VERB " "

# Definitions for various parts of speech
ADVERB    ::= ADV " " | WHEN STATEMENT " " | IF STATEMENT " " | GERUND " " | PREP " " NP " "

ADJECTIVE ::= GERUND " " | PREP " " NP " " | ADJ " "



CLAUSE    ::= ADJECTIVE+ ADVERB+ SUBJECT VERB

FOGHORN   ::= (PREP "-")? (NP "-")? OBJECT
GERUND    ::= FOGHORN | GER

# Additional Structures
WHEN      ::= "when " | "whereby " | "until " | "unless "
IF        ::= "not "? ("if " | "only if " | "because ")
AND       ::= "and " | "but " | "or "

# Root words
NP       ::= ("a " | "the ") ADJ+ NOUN
PREP     ::= "not"? ("to " | "onto " | "into " | "of " | "out of " | "in " | "within " | "by " | "with " | "without ")
ADJ      ::= "purple " | "smelly " | "happy " | "windy " | "unbelievable "
ADV      ::= "quicky " | "slowly " | "happily "
NOUN     ::= "cat " | "dog " | "man "
LOCATION ::= NP
SUBJECT  ::= NP
OBJECT   ::= NP

# includes object for transient/intransitive use of verbs
VERB      ::= "berate " OBJECT? " " | "stop " OBJECT? " " | "flee " OBJECT? " " | "put " OBJECT LOCATION+
GER       ::= "berating " | "stopping " | "fleeing " | "putting "